# Generated by Django 2.2.7 on 2019-11-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191120_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reading_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reading Time'),
        ),
    ]
